# Configuración de Yarn Berry (v4+)
# Usar corepack para manejar Yarn automáticamente

nodeLinker: node-modules

# No especificar yarnPath - dejar que corepack lo maneje
# Corepack buscará la versión especificada en package.json (packageManager field)
# Ejecuta: corepack enable && corepack prepare yarn@4.5.0 --activate

# Habilitar PnP si prefieres (descomenta la siguiente línea y comenta nodeLinker)
# nodeLinker: pnp
